### ISSUE TITLE
Getwork has no matching template for merkle root

### ISSUE THREAD

**Issue by sammy007** [decred/cgminer#13]
I am not sure this is appropriate place for this report, but as we can see there was no race or something that can cause this rejected block. Maybe cgminer has some bug and produced invalid blocks or maybe it's normal or even dcrd problem. Can anyone highlight what happened?

```
15:53:25 2016-02-06 [INF] BMGR: Processed 1 block in the last 2m10.71s (1 transaction, height 8449, 2016-02-06)
15:53:50 2016-02-06 [ERR] RPCS: Block submitted via getwork has no matching template for merkle root 530e7e527e8ed3d32f586ab8e955c18cd82357700dabdbd740ab708e4be67cfe
15:55:07 2016-02-06 [INF] BMGR: Processed 1 block in the last 1m41.95s (1 transaction, height 8450, 2016-02-06)
```

**Comment by ocminer** [comment]
I can confirm this from my side

**Comment by cjepson** [comment]
Fixed internally already, will be patched in the mainnet release.
