### ISSUE TITLE
Distribute work for multi-GPU setup

### ISSUE THREAD

**Issue by sammy007** [decred/cgminer#15]
Running N instances of cgminer for N-GPU per rig setups is a nonsense and absolutely unacceptable. Cgminer should properly distribute work between GPUs and don't require weird setups.

Reference https://github.com/decred/cgminer/issues/5#issuecomment-181027070

**Comment by chappjc** [comment]
Is a fix planned for this?  Between this issue and high CPU usage, AMD setups are a pain.

**Comment by chappjc** [comment]
Running multiple cgminer instances does not appear to be a feasible solution for me.  When I run 2 instances for 2 different GPUs, both miners slow down by more than half of hash rate they would achieve alone.  However, if I use both GPU in the same cgminer, they both sceam.

Whatever pathological process is causing very high CPU load in one instance is likely to be causing an even more severe issue when you try to run 2 processes.

**Comment by jcvernaleo** [comment]
Closing since this repo is no longer being maintained.
