### ISSUE TITLE
Strange GPU load chart

### ISSUE THREAD

**Issue by sammy007** [decred/cgminer#17]
While mining directly to daemon I measured GPU load and it's far from being perfect:

![screen shot 2016-02-09 at 14 18 16](https://cloud.githubusercontent.com/assets/7374093/12912098/44f9ff64-cf38-11e5-9d14-0bf20dd82202.png)

My setup is simple: several multi-GPU rigs -> haproxy (http balancer to avoid tls requirements) -> dcrd

Also while mining I always see that <code>Pool 0 not providing work fast enough</code> report by cgminer. Can anyone highlight how to get rid of these warnings to achieve decent GPU load?

**Comment by jolan** [comment]
This is likely fixed by #24 or #27.  Please re-open if that's not the case.
