### ISSUE TITLE
Improper reversal of sent hash

### ISSUE THREAD

**Issue by ocminer** [decred/cgminer#18]
I see improper reversal of sent hash from cgminer occasionally on my pool.

I expect 12345678 for example but the miner sends 87654321 which then leads to a rejected share as I'm verifying the getwork request/answer. 

I do not see that on the linux version (yet) - so it seems to be a win issue with version 0.0.4

**Comment by cjepson** [comment]
Which field has endianness issues? getwork responses are a valid header that meets target.

**Comment by jcvernaleo** [comment]
Closing since this repo is no longer maintained.
