### ISSUE TITLE
If work is queued, it's returned from queue in wrong order

### ISSUE THREAD

**Issue by ocminer** [decred/cgminer#21]
According to my research this:

https://github.com/decred/cgminer/blob/3.7/cgminer.c#L4284

Is still referencing to "old" work and to the wrong place in the hash resulting in a wrong reversal/copy of the work so if work comes from the queue, it's "unknown-work" to the pool because it gets reversed/hashed wrong. 

Work gets pushed here:
https://github.com/decred/cgminer/blob/3.7/cgminer.c#L4416

**Comment by jcvernaleo** [comment]
Closing since this repo is no longer maintained.
