### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by feeleep75** [decred/cgminer#22]
Can anyone share comlete MinGW toolchain to compile it without errors?

**Comment by chappjc** [comment]
What kind of errors do you get?  It is not known to be broken.

**Comment by jcvernaleo** [comment]
@feeleep75 we just committed a script to simplify build for windows from Linux with mingw.  Does that help or were you looking for something different?

**Comment by jcvernaleo** [comment]
I actually think this one was solved anyway so just closing (and the repo is no longer maintained).
