### ISSUE TITLE
Fan Control

### ISSUE THREAD

**Issue by rogueops** [decred/cgminer#23]
Seems that fan control is no longer working.

**Comment by chappjc** [comment]
And --auto-gpu causes blue screens when quitting cgminer.

**Comment by gh0stshell** [comment]
gpu-vddc also does nothing

**Comment by gh0stshell** [comment]
i set my fan to 70-90 and it stays below that

**Comment by rogueops** [comment]
tried

--gpu-fan

and

--auto-fan

and both options no longer listed even when checking -h

same with --gpu-vddc

**Comment by rogueops** [comment]
got it all figured out and got all my options back!

you can close this ticket

I got it all working for linux if anyone needs help

**Comment by rogueops** [comment]
holy cow my temps are way lower, my new cgminer is working perfectly!

**Comment by chappjc** [comment]
You can choose this issue.  But first, why don't you share what solved it?

**Comment by jcvernaleo** [comment]
Closing this issue since it looks like nothing more is happening here but it would have been nice if the solution was posted here.
