### ISSUE TITLE
Please make TLS-enabled windows build of cgminer.

### ISSUE THREAD

**Issue by sammy007** [decred/cgminer#4]
According to some rumours on #decred windows build of cgminer lacks tls support. According to decrd help <code>--notls Disable TLS for the RPC server -- NOTE: This is only allowed if the RPC server is bound to localhost</code> so it turns out that it's impossible to mine on remote node from windows machines. Is it big deal to make tls-enabled cgminer build for windows?

**Comment by chappjc** [comment]
I don't know how the official build was done, but the curl dll packaged in the zip doesn't seem to require any other tls-related libraries.  When I made a Win64 build ([see here](https://github.com/decred/cgminer/pull/3#commitcomment-15750927)), there were many dependencies (required dlls) stemming from libcurl-4.dll.  These include libssh2-1.dll and ssleay32.dll (but no gnutls lib).  I supposed it's possible they are all statically linked in the official build, but I doubt that given the file size.  I can share the binaries I generated, if you would like.  Although, I don't know if TLS is used elsewhere besides curl.

**Comment by davecgh** [comment]
I also just submitted a pr which allows it to accept `--cert` (#6).  With that in conjunction with @chappjc's PR (#3), I was able to get it working on windows with TLS.

```
0: Enabled Alive Quota 1 Prio 0: https://127.0.0.1:19109  User:<username>
```

**Comment by sammy007** [comment]
Forced tls is a nonsense, in a trusted network it's just an overhead and waste of time. The right way is completely not force tls, let user decide how to deploy. Hope we will be able to at least use cgminer with tls but without cert check.

**Comment by davecgh** [comment]
The project announced the code will be released a day before launch.  Feel free to fork it and make whatever changes you want for your local setup.

**Comment by sammy007** [comment]
LOL good luck.

**Comment by davecgh** [comment]
You made an issue about it not supporting TLS.  The title is "Please make TLS-enabled windows build of cgminer".  I provided a PR that does exactly that and allows it to support it.  I have no idea why you feel the need to act like a total jerk, but good luck to you.

**Comment by sammy007** [comment]
@davecgh I still hope you are not part of decred team, idiot.

**Comment by sammy007** [comment]
Removed some emotional rush, sorry.

**Comment by chappjc** [comment]
It seems to me that TLS support might already be there, although difficult to configure.

With a MinGW distribution installed, it's possible to update trusted the CA certificates on Windows.  The curl library has a hard-coded path to the consolidated list of trusted certs (e.g. /ming64/ssl/certs/ca-bundle.crt), so the question is if this is relative to working directory when running from a regular Windows command line.  In MSYS2 the package mingw64/mingw-w64-x86_64-ca-certificates provides a script called `update-ca-trust` that updates the CA certificate bundle.  Also available is the `trust` command referenced in the Arch instructions on the Decred Wiki.

I don't see hacking curl code itself as a good option.  So, the question is, can the base ca certificates file be distributed in this folder, and is there a clean way to support updating the certificate files like the above mentioned tools do?

**Comment by jcvernaleo** [comment]
I don't have windows to test with.  Do PR#3 and PR#6 (both of which have been merged in) take care of this issue?  If so I'd like to close it.  If not, what else do we need?

**Comment by sammy007** [comment]
I have no build environment to produce .exe for testing. It always was a magick, so I will be waiting for next bunch of blobs to be able to test it.

**Comment by jcvernaleo** [comment]
This is handled in the recent v0.0.2 builds.
