### ISSUE TITLE
cgminer submit same block several times

### ISSUE THREAD

**Issue by sammy007** [decred/cgminer#5]
I was mining with 2 GPUs and sometimes same blocks got submitted twice, indeed 2nd block submission failed and nothing worst happened, but that's affect measurement and stats.

**Comment by cjepson** [comment]
Temporary fix is on this branch. You need to start your miners in separate cgminer instances per GPU for it to work.

https://github.com/cjepson/cgminer/tree/cj_fixes2

A fix that is less of a hack is in the works.

**Comment by sammy007** [comment]
So 5xGPU rig with single cgminer instance doing the same as 1xGPU rig in terms of profitability? If there will be no fix for this issue before mainnet launch, can you imagine what fail it will be?
- Most solid pools prohibit duplicate shares and banning immediately on first attempt to submit duplicate share
- Solo mining goes to nowhere if 5xGPU actually perform like 1xGPU.

Since decred getwork is even much more bandwidth consuming than bitcoin-like getwork, single rig with several GPUs will increase bandwidth dramatically. Sometimes even 100MB is not enough, what if someone decide (like me) to run a remote node and point several hundreds GPUs there? Not everyone has such an internet connection.

**Comment by ocminer** [comment]
I can confirm this. And I first thought my getwork implementation is off :)

**Comment by sammy007** [comment]
Is it included in recent 0.0.2 build?

**Comment by jcvernaleo** [comment]
Yes, the 0.0.2 build should has everything in the current master (commit c172a7a62455fae62afdc7995021f5c046aab9d7 )

**Comment by sammy007** [comment]
So mult-GPU rigs still must run an instance of cgminer per-GPU? Is it possible to fix it properly?

**Comment by sammy007** [comment]
Can anyone from core make a clear statement regarding multi cgminer instances? Thanks for the fix, but it's still unacceptable to run N instances of cgminer for N-GPU rigs. Is it possible to randomize/parallelize it without forcing miners to run weird setups, it's near impossible to manage that properly. Maybe it works as expected and description is just wrong, I don't understand this code 100%, but clear statement would be appreciated.

**Comment by jcvernaleo** [comment]
@sammy007 at the moment, yes, the best practice still one instance per GPU.  Not ideal for sure, but the best we have at the moment.  Feel free to open an new issue requesting that feature if you want (since that would be much easier to track than if we keep discussing on a closed issue).
